name: Build Opus

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install v141 toolset for VS2022
        shell: pwsh
        run: |
          $vsInstaller = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vs_installer.exe"
          if (Test-Path $vsInstaller) {
            & $vsInstaller modify --installPath "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise" --add Microsoft.VisualStudio.Component.VC.v141 --wait --norestart -PassThru
          } else {
            Write-Error "Visual Studio installer not found at $vsInstaller"
          }

      - name: Setup MSBuild and Developer Environment
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Download Opus
        run: |
          git clone https://github.com/xiph/opus.git
          cd opus
          git fetch --tags
          git checkout v1.5.2

      - name: Build Opus x86
        shell: cmd
        run: |
          cd opus
          cmake -S . -B build/x86 -G "Visual Studio 17 2022" -A Win32 -T v141 -DBUILD_SHARED_LIBS=ON ^
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=%cd%/build/Release/x86 ^
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=%cd%/build/Release/x86
          msbuild build/x86/opus.sln /p:Configuration=Release /p:Platform=Win32

      - name: Build Opus x64
        shell: cmd
        run: |
          cd opus
          cmake -S . -B build/x64 -G "Visual Studio 17 2022" -A x64 -T v141 -DBUILD_SHARED_LIBS=ON ^
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=%cd%/build/Release/x64 ^
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=%cd%/build/Release/x64
          msbuild build/x64/opus.sln /p:Configuration=Release /p:Platform=x64

      - name: Collect artifacts
        shell: cmd
        run: |
          set OPUS_VER=1.5.2
          mkdir artifacts
          mkdir artifacts\include
          mkdir artifacts\lib_x86
          mkdir artifacts\lib_x64

          copy opus\build\Release\x86\*.dll artifacts\lib_x86\
          copy opus\build\Release\x86\*.lib artifacts\lib_x86\

          copy opus\build\Release\x64\*.dll artifacts\lib_x64\
          copy opus\build\Release\x64\*.lib artifacts\lib_x64\

          xcopy opus\include artifacts\include /E /I /Y

          powershell Compress-Archive -Path artifacts\* -DestinationPath opus-%OPUS_VER%.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opus-1.5.2
          path: opus-1.5.2.zip
