name: Build Opus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install v141 XP toolset for VS2022
        shell: pwsh
        run: |
          # Use the correct path for Visual Studio installer on windows-2022
          $vsInstaller = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vs_installer.exe"
          if (Test-Path $vsInstaller) {
            & $vsInstaller modify --installPath "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise" --add Microsoft.VisualStudio.Component.VC.v141.xp --quiet --norestart
          } else {
            Write-Error "Visual Studio installer not found at $vsInstaller"
          }

      - name: Download Opus
        run: |
          git clone https://github.com/xiph/opus.git
          cd opus
          git fetch --tags
          git checkout v1.5.2

      - name: Build Opus x86 & x64 for Windows XP
        shell: cmd
        run: |
          set "VS2022_PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          cd opus

          rem --- x86 Build for XP ---
          echo "Setting up Visual Studio x86 environment..."
          call "%VS2022_PATH%\VC\Auxiliary\Build\vcvarsall.bat" x86

          echo "Creating and navigating to x86 build directory..."
          mkdir build_x86
          cd build_x86

          echo "Running CMake for x86 with v141_xp toolset..."
          rem This -T v141_xp flag is the correct way to select the XP toolset
          cmake .. -G "Visual Studio 17 2022" -A Win32 -T v141_xp

          echo "Building x86 Release..."
          msbuild opus.sln /p:Configuration=Release /p:Platform=Win32
          
          cd ..

          rem --- x64 Build for XP ---
          echo "Setting up Visual Studio x64 environment..."
          call "%VS2022_PATH%\VC\Auxiliary\Build\vcvarsall.bat" x64

          echo "Creating and navigating to x64 build directory..."
          mkdir build_x64
          cd build_x64

          echo "Running CMake for x64 with v141_xp toolset..."
          rem This -T v141_xp flag is the correct way to select the XP toolset
          cmake .. -G "Visual Studio 17 2022" -A x64 -T v141_xp

          echo "Building x64 Release..."
          msbuild opus.sln /p:Configuration=Release /p:Platform=x64
          
          cd ..

      - name: Collect artifacts
        shell: cmd
        run: |
          echo "--- Listing x86 build directory contents ---"
          dir /s opus\build_x86

          echo "--- Listing x64 build directory contents ---"
          dir /s opus\build_x64```

          set OPUS_VER=1.5.2
          mkdir artifacts
          mkdir artifacts\include
          mkdir artifacts\lib_x86
          mkdir artifacts\lib_x64

          rem The DLL and the import LIB are in the Release sub-folder
          echo "Copying x86 libraries..."
          copy opus\build_x86\Release\*.dll artifacts\lib_x86\
          copy opus\build_x86\Release\*.lib artifacts\lib_x86\

          rem The DLL and the import LIB are in the Release sub-folder
          echo "Copying x64 libraries..."
          copy opus\build_x64\Release\*.dll artifacts\lib_x64\
          copy opus\build_x64\Release\*.lib artifacts\lib_x64\

          echo "Copying include files..."
          xcopy opus\include artifacts\include /E /I /Y

          echo "Zipping artifacts..."
          powershell Compress-Archive -Path artifacts\* -DestinationPath opus-%OPUS_VER%-xp.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opus-1.5.2-xp
          path: opus-1.5.2-xp.zip
