name: Build Opus

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Download Opus
        run: |
          git clone https://github.com/xiph/opus.git
          cd opus
          git fetch --tags
          git checkout v1.5.2

      - name: Build Opus x86
        shell: cmd
        run: |
          cd opus
          echo "Configuring x86 build..."
          cmake -S . -B build/x86 -G "Visual Studio 17 2022" -A Win32 -DBUILD_SHARED_LIBS=ON
          if %ERRORLEVEL% neq 0 (
            echo "CMake configuration failed for x86"
            exit /b 1
          )
          echo "Building x86..."
          cmake --build build/x86 --config Release
          if %ERRORLEVEL% neq 0 (
            echo "Build failed for x86"
            exit /b 1
          )

      - name: Build Opus x64
        shell: cmd
        run: |
          cd opus
          echo "Configuring x64 build..."
          cmake -S . -B build/x64 -G "Visual Studio 17 2022" -A x64 -DBUILD_SHARED_LIBS=ON
          if %ERRORLEVEL% neq 0 (
            echo "CMake configuration failed for x64"
            exit /b 1
          )
          echo "Building x64..."
          cmake --build build/x64 --config Release
          if %ERRORLEVEL% neq 0 (
            echo "Build failed for x64"
            exit /b 1
          )

      - name: Find and collect artifacts
        shell: cmd
        run: |
          cd opus
          echo "Searching for generated files..."
          
          echo "=== x86 build directory structure ==="
          dir build\x86 /s /b | findstr /E "\.dll \.lib \.exe"
          
          echo "=== x64 build directory structure ==="
          dir build\x64 /s /b | findstr /E "\.dll \.lib \.exe"
          
          echo "=== Creating artifacts directory ==="
          cd ..
          set OPUS_VER=1.5.2
          mkdir artifacts
          mkdir artifacts\include
          mkdir artifacts\lib_x86
          mkdir artifacts\lib_x64

          echo "Collecting x86 artifacts..."
          for /r opus\build\x86 %%f in (*.dll) do (
            echo Found x86 DLL: %%f
            copy "%%f" artifacts\lib_x86\
          )
          for /r opus\build\x86 %%f in (*.lib) do (
            echo Found x86 LIB: %%f
            copy "%%f" artifacts\lib_x86\
          )

          echo "Collecting x64 artifacts..."
          for /r opus\build\x64 %%f in (*.dll) do (
            echo Found x64 DLL: %%f
            copy "%%f" artifacts\lib_x64\
          )
          for /r opus\build\x64 %%f in (*.lib) do (
            echo Found x64 LIB: %%f
            copy "%%f" artifacts\lib_x64\
          )

          echo "Collecting headers..."
          xcopy opus\include artifacts\include /E /I /Y

          echo "=== Final artifact contents ==="
          dir artifacts /s

          echo "Creating zip archive..."
          powershell Compress-Archive -Path artifacts\* -DestinationPath opus-%OPUS_VER%.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opus-1.5.2
          path: opus-1.5.2.zip
