name: Build Opus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install v141 XP toolset for VS2022
        run: '"C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Installer\vs_installer.exe" modify --add Microsoft.VisualStudio.Component.VC.v141.xp --quiet --norestart'
        shell: pwsh

      - name: Download Opus
        run: |
          git clone https://github.com/xiph/opus.git
          cd opus
          git fetch --tags
          git checkout v1.5.2

      - name: Build Opus x86 & x64
        shell: cmd
        run: |
          set VS2022_PATH=C:\Program Files\Microsoft Visual Studio\2022\BuildTools

          rem --- x86 Build ---
          call "%VS2022_PATH%\VC\Auxiliary\Build\vcvarsall.bat" x86 -xp
          cd opus
          mkdir build_x86
          cd build_x86
          cmake .. -G "Visual Studio 17 2022" -A Win32 -T v141_xp
          msbuild opus.sln /p:Configuration=Release /p:Platform=Win32 /p:XPDeprecationWarning=false
          cd ..

          rem --- x64 Build ---
          call "%VS2022_PATH%\VC\Auxiliary\Build\vcvarsall.bat" x64 -xp
          mkdir build_x64
          cd build_x64
          cmake .. -G "Visual Studio 17 2022" -A x64 -T v141_xp
          msbuild opus.sln /p:Configuration=Release /p:Platform=x64 /p:XPDeprecationWarning=false
          cd ..

      - name: Collect artifacts
        shell: cmd
        run: |
          set OPUS_VER=1.5.2
          mkdir artifacts
          mkdir artifacts/include
          mkdir artifacts/dll_x86
          mkdir artifacts/dll_x64

          rem x86 dll / lib
          for /r build_x86 %%f in (*.dll *.lib) do copy "%%f" artifacts\dll_x86\

          rem x64 dll / lib
          for /r build_x64 %%f in (*.dll *.lib) do copy "%%f" artifacts\dll_x64\

          xcopy opus\include artifacts\include /E /I /Y

          powershell Compress-Archive -Path artifacts\* -DestinationPath opus-%OPUS_VER%-xp.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opus-1.5.2-xp
          path: opus-1.5.2-xp.zip
