name: Build Opus

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Download Opus
        run: |
          git clone https://github.com/xiph/opus.git
          cd opus
          git fetch --tags
          git checkout v1.5.2

      - name: Build Opus x86
        shell: cmd
        run: |
          cd opus
          echo "Configuring x86 build..."
          cmake -S . -B build/x86 -G "Visual Studio 17 2022" -A Win32 -DBUILD_SHARED_LIBS=ON ^
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=%cd%/build/Release/x86 ^
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=%cd%/build/Release/x86
          if %ERRORLEVEL% neq 0 (
            echo "CMake configuration failed for x86"
            exit /b 1
          )
          echo "Building x86..."
          msbuild build/x86/opus.sln /p:Configuration=Release /p:Platform=Win32
          if %ERRORLEVEL% neq 0 (
            echo "MSBuild failed for x86"
            exit /b 1
          )

      - name: Build Opus x64
        shell: cmd
        run: |
          cd opus
          echo "Configuring x64 build..."
          cmake -S . -B build/x64 -G "Visual Studio 17 2022" -A x64 -DBUILD_SHARED_LIBS=ON ^
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=%cd%/build/Release/x64 ^
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=%cd%/build/Release/x64
          if %ERRORLEVEL% neq 0 (
            echo "CMake configuration failed for x64"
            exit /b 1
          )
          echo "Building x64..."
          msbuild build/x64/opus.sln /p:Configuration=Release /p:Platform=x64
          if %ERRORLEVEL% neq 0 (
            echo "MSBuild failed for x64"
            exit /b 1
          )

      - name: Collect artifacts
        shell: cmd
        run: |
          set OPUS_VER=1.5.2
          mkdir artifacts
          mkdir artifacts\include
          mkdir artifacts\lib_x86
          mkdir artifacts\lib_x64

          echo "Collecting x86 artifacts..."
          copy opus\build\Release\x86\*.dll artifacts\lib_x86\ 2>nul || echo "No x86 DLLs found"
          copy opus\build\Release\x86\*.lib artifacts\lib_x86\ 2>nul || echo "No x86 LIBs found"

          echo "Collecting x64 artifacts..."
          copy opus\build\Release\x64\*.dll artifacts\lib_x64\ 2>nul || echo "No x64 DLLs found"
          copy opus\build\Release\x64\*.lib artifacts\lib_x64\ 2>nul || echo "No x64 LIBs found"

          echo "Collecting headers..."
          xcopy opus\include artifacts\include /E /I /Y

          echo "Creating zip archive..."
          powershell Compress-Archive -Path artifacts\* -DestinationPath opus-%OPUS_VER%.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4

        with:
          name: opus-1.5.2
          path: opus-1.5.2.zip
